### ISSUE TITLE
Ambiguous use of 'length'

### ISSUE THREAD

**Issue by dayjer** [NextFaze/FazeKit#6]
https://cl.ly/2M1A3W1y1R1g

FazeKit makes it difficult to use String.length.

**Comment by ricsantos** [comment]
Thanks @dayjer keeping us busy!

**Comment by ricsantos** [comment]
Swift 4 feature branch is now being reviewed, #7

**Comment by ricsantos** [comment]
Fixed as of [FazeKit 2.0](https://github.com/NextFaze/FazeKit/releases/tag/2.0)
